### ISSUE TITLE
Out of date documentation

### ISSUE THREAD

**Issue by devgibsonsp** [valincius/BlazorScheduler#20]
Looks like your documentation is out of date. Appointment does not contain a Title property.

**Comment by valincius** [comment]
Hi, `Appointment` will now be a object that you create in the latest version.

I am still working on demos to show the `Appointment` templating under the scheduler (I also realize the naming might not be the best)

Please have a look at https://github.com/valincius/BlazorScheduler/blob/main/DemoApp/Pages/Basic.razor to see the usage
