### ISSUE TITLE
Static Calendar View?

### ISSUE THREAD

**Issue by devgibsonsp** [valincius/BlazorScheduler#21]
This component works great for my usecase, however I was wondering if you planned on implementing a static calendar view config option? I currently need to be able to allow an administrator to schedule through the calendar, but also allow users to view the calendar without being able to add appointments. It seems that currently it is not possible to disable the onClick being triggered by clicking on days of the week.

**Comment by valincius** [comment]
Hi, you can do so by setting `DisableDragging` to `true`

```
<Scheduler Config="_config">...</Scheduler>

@code {
  Config _config = new {
    DisableDragging = true
  };
}
```

Does this do what you're looking for?
I realize it may be a little cumbersome to have to create the `Config` object just to change this, I could set this as a parameter on the `Scheduler` - I am still figuring out the API design.

**Comment by devgibsonsp** [comment]
Ah, sorry. I was confused by the vernacular. The config object is reasonable. Thanks!
