### ISSUE TITLE
Rendering problem on my blazor server

### ISSUE THREAD

**Issue by mohamedTK** [valincius/BlazorScheduler#26]
**Describe the bug**
After installing BlazorScheduler on my blazor server project, I seem to be running into a rendering problem at runtime. The exact error I ran into is the following:

**An unhandled exception occurred while processing the request.
InvalidOperationException: JavaScript interop calls cannot be issued at this time. This is because the component is being statically rendered. When prerendering is enabled, JavaScript interop calls can only be performed during the OnAfterRenderAsync lifecycle method.**

How should I adress this problem?

**To Reproduce**
1. Intalling bazorScheduler on my Blazor server
2. Running my project with `dotnet run` command
3. See error

**Expected behavior**
No errors at runtime and my BlazorScheduler component correctly rendered.

**Screenshots**
![image](https://user-images.githubusercontent.com/50345421/138115116-c07551fd-a599-4a40-a3c2-02ea13d57a5c.png)

**Additional context**
N.A.

**Comment by valincius** [comment]
Thank you for creating this issue. I will have a look and get back to you.
