### ISSUE TITLE
Remove start and end time?

### ISSUE THREAD

**Issue by johanf82** [valincius/BlazorScheduler#49]
When I add appointments, from 13.00 till 14.00 for example, I always see the title with de start and end time. Is there a way to remove the times and just show the title? It kinda sits in the way with my implementation.
This data is not shown for full-day appointments, but I don't have these.

Thank you.

**Comment by valincius** [comment]
Thank you for the suggestion. I think this makes sense and I will remove this by default - it can be added via the day template if someone needs it.

I will get this change in by the end of the day.
