### ISSUE TITLE
Appointments covered by next row when MaxVisibleAppointmentsPerDay > 5

### ISSUE THREAD

**Issue by dennisrahmen** [valincius/BlazorScheduler#57]
**Describe the bug**
When MaxVisibleAppointmentsPerDay > 5 then the appointments after that will be covered by the next row, since the height of the row does not adjust accordingly.

**To Reproduce**
1. Set MaxVisibleAppointmentsPerDay to 7
2. Add 7 appointments

**Additional context**
Already fixed here: https://github.com/valincius/BlazorScheduler/pull/56

**Comment by valincius** [comment]
Fixed in #56
