### ISSUE TITLE
CSS used ? 

### ISSUE THREAD

**Issue by kmvickers** [valincius/BlazorScheduler#9]
A question: 

What CSS are you using with this component . I am going to try using it alongside MUDBlazor

thanks 
Kevin

**Comment by valincius** [comment]
> A question: 
> 
> 
> 
> What CSS are you using with this component . I am going to try using it alongside MUDBlazor
> 
> 
> 
> 
> 
> thanks 
> 
> Kevin 

Hi, I wrote all the CSS for this library, I do not use any external css libraries. 
I use this component in my own MudBlazor app and it fits right in, but let me know if there's any changes that can be made for it to suite you better, or submit your own PR :)
